# Allow for anyone to create same environment with this docker-compose.yml config file
# https://docs.docker.com/compose/wordpress/
# This specific work env adds the wp-content/plugins folder of WordPress install automatically
version: '3.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      #   - wordpress:/var/www/html // specific themes
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    restart: always
    ports:
      - 8888:80
    volumes:
      - ../wp-content:/var/www/html/wp-content
      - ./:/var/www/html/wp-content/plugins/article-recommendations
    #   - ./path/to/my-plugin:/var/www/html/wp-content/plugins/my-plugin  // plugins to develop
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  micro:
    container_name: micro
    image: snowplow/snowplow-micro:1.0.0
    restart: always
    ports:
      - '9090:9090'
    command: '--collector-config /config/micro.conf --iglu /config/iglu.json'
    volumes:
      - ./micro:/config
volumes:
  db_data: {}
