# Allow for anyone to create same environment with this docker-compose.yml config file
# This specific work env adds the wp-content/plugins folder of WordPress install automatically
version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./:/var/www/html/wp-content/plugins/article-recommendations
    #   - ./path/to/my-plugin:/var/www/html/wp-content/plugins/my-plugin  // plugins to develop

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    #   - wordpress:/var/www/html // specific themes
      - database:/var/lib/mysql
